# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extension_kind.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xtension_kind.proto\x12\x18spotify.extendedmetadata*w\n\rExtensionKind\x12\x1e\n\x1a\x45XTENSION_KIND_UNSPECIFIED\x10\x00\x12\x0c\n\x08TRACK_V4\x10\x01\x12\x0c\n\x08\x41LBUM_V4\x10\x02\x12\r\n\tARTIST_V4\x10\x03\x12\x0b\n\x07SHOW_V4\x10\x04\x12\x0e\n\nEPISODE_V4\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_kind_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTENSIONKIND._serialized_start=50
  _EXTENSIONKIND._serialized_end=169
# @@protoc_insertion_point(module_scope)
