# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extended_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import extension_kind_pb2 as extension__kind__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xtended_metadata.proto\x12\x18spotify.extendedmetadata\x1a\x14\x65xtension_kind.proto\"W\n\x14\x42\x61tchedEntityRequest\x12?\n\x0e\x65ntity_request\x18\x01 \x03(\x0b\x32\'.spotify.extendedmetadata.EntityRequest\"\\\n\rEntityRequest\x12\x12\n\nentity_uri\x18\x01 \x01(\t\x12\x37\n\x05query\x18\x02 \x03(\x0b\x32(.spotify.extendedmetadata.ExtensionQuery\"Q\n\x0e\x45xtensionQuery\x12?\n\x0e\x65xtension_kind\x18\x01 \x01(\x0e\x32\'.spotify.extendedmetadata.ExtensionKind\"a\n\x18\x42\x61tchedExtensionResponse\x12\x45\n\x11\x65xtended_metadata\x18\x01 \x03(\x0b\x32*.spotify.extendedmetadata.ExtendedMetadata\"p\n\x10\x45xtendedMetadata\x12\x12\n\nentity_uri\x18\x01 \x01(\t\x12H\n\x0e\x65xtension_data\x18\x02 \x03(\x0b\x32\x30.spotify.extendedmetadata.ExtensionDataContainer\"\x9a\x01\n\x16\x45xtensionDataContainer\x12?\n\x0e\x65xtension_kind\x18\x01 \x01(\x0e\x32\'.spotify.extendedmetadata.ExtensionKind\x12?\n\x0e\x65xtension_data\x18\x02 \x01(\x0b\x32\'.spotify.extendedmetadata.ExtensionData\"\x1e\n\rExtensionData\x12\r\n\x05value\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extended_metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATCHEDENTITYREQUEST._serialized_start=75
  _BATCHEDENTITYREQUEST._serialized_end=162
  _ENTITYREQUEST._serialized_start=164
  _ENTITYREQUEST._serialized_end=256
  _EXTENSIONQUERY._serialized_start=258
  _EXTENSIONQUERY._serialized_end=339
  _BATCHEDEXTENSIONRESPONSE._serialized_start=341
  _BATCHEDEXTENSIONRESPONSE._serialized_end=438
  _EXTENDEDMETADATA._serialized_start=440
  _EXTENDEDMETADATA._serialized_end=552
  _EXTENSIONDATACONTAINER._serialized_start=555
  _EXTENSIONDATACONTAINER._serialized_end=709
  _EXTENSIONDATA._serialized_start=711
  _EXTENSIONDATA._serialized_end=741
# @@protoc_insertion_point(module_scope)
